FROM tensorflow/tensorflow:2.3.1
COPY ./requirements.txt ./requirements.txt
RUN python3 -m pip install -r ./requirements.txt
RUN apt update && apt install -y libsndfile1 sox libgomp1  libpthread-stubs0-dev iputils-ping graphviz
WORKDIR /app


