FROM tensorflow/tensorflow:2.4.1
COPY ./requirements.txt ./requirements.txt
RUN python3 -m pip install -r ./requirements.txt
RUN apt update && apt install -y libsndfile1 sox libgomp1  libpthread-stubs0-dev iputils-ping graphviz

RUN mkdir -p /usr/local/share/nltk_data
RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data punkt


RUN python3 -m pip install seaborn

WORKDIR /app


