FROM tensorflow/tensorflow:2.3.1
COPY ./requirements.txt ./requirements.txt
RUN python3 -m pip install -r ./requirements.txt
RUN apt update && apt install -y libsndfile1 sox graphviz libgomp1  libpthread-stubs0-dev

RUN python3 -m pip install -Iv deepspeech==0.8.2

RUN python3 -m install pyaudio
RUN apt-get install -y alsa-base alsa-utils libportaudio2 portaudio19-dev

RUN python3 -m pip install halo

RUN python3 -m pip install wave

RUN apt-get install -y ffmpeg

WORKDIR /app


